services:
  postgres:
    image: postgres:15
    container_name: bg-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bg-network

  kafka:
    image: apache/kafka:latest
    container_name: bg-kafka
    ports:
      - "9999:9999"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:29093,PLAINTEXT_HOST://0.0.0.0:9999
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9999
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - bg-network

  user-service:
    #build: ./usermicroservice
    image: ${WAYNE_DOCKER_USERNAME}/usermicroservice:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-server:8761/eureka/
      - USER_DB_URL=jdbc:postgresql://postgres:5432/usermicroservice
      - DB_USERNAME=${DB_USERNAME}
      - USER_DB_PASSWORD=${DB_PASSWORD}
      - SPRING_PORT=8081
      - EUREKA_USERNAME=${EUREKA_USERNAME}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD}
      - EUREKA_HOST=${EUREKA_HOST}
    ports:
      - "8081:8081"
    #depends_on:
      #eureka-server:
        #condition: service_healthy
    networks:
      - bg-network

  listing-service:
    #build: ./listingmicroservice
    image: ${WAYNE_DOCKER_USERNAME}/listingmicroservice:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-server:8761/eureka/
      - LISTING_DB_URL=jdbc:postgresql://postgres:5432/listingmicroservice
      - DB_USERNAME=${DB_USERNAME}
      - LISTING_DB_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_PORT=8082
      - EUREKA_USERNAME=${EUREKA_USERNAME}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD}
      - EUREKA_HOST=${EUREKA_HOST}
    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_started
    networks:
      - bg-network

  transaction-service:
    #build: ./transactionmicroservice
    image: ${WAYNE_DOCKER_USERNAME}/transactionmicroservice:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-server:8761/eureka/
      - TRANSACTION_DB_URL=jdbc:postgresql://postgres:5432/transactionmicroservice
      - DB_USERNAME=${DB_USERNAME}
      - TRANSACTION_DB_PASSWORD=${DB_PASSWORD}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SPRING_PORT=8084
    ports:
      - "8084:8084"
    networks:
      - bg-network

  notification-service:
    #build: ./notificationmicroservice
    image: ${WAYNE_DOCKER_USERNAME}/notificationmicroservice:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-server:8761/eureka/
      - NOTIFICATION_DB_URL=jdbc:postgresql://postgres:5432/notificationmicroservice
      - DB_USERNAME=${DB_USERNAME}
      - NOTIFICATION_DB_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_PORT=8085
    ports:
      - "8085:8085"
    depends_on:
      kafka:
        condition: service_started
    networks:
      - bg-network

  reporting-service:
    #build: ./reportingmicroservice
    image: ${WAYNE_DOCKER_USERNAME}/reportingmicroservice:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-server:8761/eureka/
      - REPORTING_DB_URL=jdbc:postgresql://postgres:5432/reportingmicroservice
      - DB_USERNAME=${DB_USERNAME}
      - REPORTING_DB_PASSWORD=${DB_PASSWORD}
      - SPRING_PORT=8087
    ports:
      - "8087:8087"
    networks:
      - bg-network

  #ai-service:
    #build: ./aimicroservice
    #image: ${WAYNE_DOCKER_USERNAME}/aimicroservice:latest
    #environment:
      #- SPRING_PROFILES_ACTIVE=docker
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-server:8761/eureka/
      #- MISTRAL_API_KEY=${MISTRAL_API_KEY}
      #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      #- AWS_REGION=us-west-1
      #- AWS_ENDPOINT=http://localstack:4566
      #- SPRING_PORT=8089
    #ports:
      #- "8089:8089"
    #depends_on:
      #localstack:
        #condition: service_started
    #networks:
      #- bg-network

  gateway-service:
    #build: ./gateway-front
    image: ${SEB_DOCKER_USERNAME}/gateway-front:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - GATEWAY_PORT=8090
      - EUREKA_USERNAME=${EUREKA_USERNAME}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD}
      - EUREKA_HOST=${EUREKA_HOST}
    ports:
      - "8090:8090"
    networks:
      - bg-network

networks:
  bg-network:
    driver: bridge