spring:
  application:
    name: gateway
  cloud:
    gateway:
          discovery:
            locator:
              enabled: true        # active la d√©couverte automatique des routes
              lower-case-service-id: true
  config:
    import: optional:file:./.env
eureka:
  client:
    service-url:
      defaultZone: http://<EUREKA_HOST>:8761/eureka/