name: AI Microservice CI/CD to Docker Hub

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "aimicroservice/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "aimicroservice/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - "4566:4566"
        volumes:
          - "./docker/localstack/init.sh:/etc/localstack/init/ready.d/init-aws.sh"
          - "./docker/localstack/data/:/tmp/data"
        env:
          SERVICES: "s3"
          GATEWAY_LISTEN: "0.0.0.0:4566"
          AWS_REGION: "us-west-1"
          ALLOW_NONSTANDARD_REGIONS: "1"

    steps:
    - name: Clean up old localstack folder
      run: sudo rm -rf ./docker/localstack || true
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: aimicroservice
      run: mvn clean package -B --file pom.xml

    - name: Run Tests (with Localstack)
      working-directory: aimicroservice
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-1
        LOCALSTACK_HOST: localhost
        LOCALSTACK_PORT: 4566
      run: mvn test

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      working-directory: aimicroservice
      run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph -DgraphFormat=json